// ffmpeg -i mp4/video01.mp4 -codec: copy -start_number 0 -hls_time 2 -hls_list_size 0 -hls_segment_size 500000 -f hls m3u8/video01.m3u8
final dataM3u8Json = {
  "page": 1,
  "per_page": 50,
  "videos": [
    "https://raw.githubusercontent.com/duythien0912/sample_short_video/main/m3u8/video01.m3u8",
    "https://raw.githubusercontent.com/duythien0912/sample_short_video/main/m3u8/video02.m3u8",
    "https://raw.githubusercontent.com/duythien0912/sample_short_video/main/m3u8/video03.m3u8",
    "https://raw.githubusercontent.com/duythien0912/sample_short_video/main/m3u8/video04.m3u8",
    "https://raw.githubusercontent.com/duythien0912/sample_short_video/main/m3u8/video05.m3u8",
    "https://raw.githubusercontent.com/duythien0912/sample_short_video/main/m3u8/video06.m3u8",
    "https://raw.githubusercontent.com/duythien0912/sample_short_video/main/m3u8/video07.m3u8",
    "https://raw.githubusercontent.com/duythien0912/sample_short_video/main/m3u8/video08.m3u8",
    "https://raw.githubusercontent.com/duythien0912/sample_short_video/main/m3u8/video09.m3u8",
    //
    "https://raw.githubusercontent.com/duythien0912/sample_short_video/main/mp4/video01.mp4",
    "https://raw.githubusercontent.com/duythien0912/sample_short_video/main/mp4/video02.mp4",
    "https://raw.githubusercontent.com/duythien0912/sample_short_video/main/mp4/video03.mp4",
    "https://raw.githubusercontent.com/duythien0912/sample_short_video/main/mp4/video04.mp4",
    "https://raw.githubusercontent.com/duythien0912/sample_short_video/main/mp4/video05.mp4",
    "https://raw.githubusercontent.com/duythien0912/sample_short_video/main/mp4/video06.mp4",
    "https://raw.githubusercontent.com/duythien0912/sample_short_video/main/mp4/video07.mp4",
    "https://raw.githubusercontent.com/duythien0912/sample_short_video/main/mp4/video08.mp4",
    "https://raw.githubusercontent.com/duythien0912/sample_short_video/main/mp4/video09.mp4",
    //
    "https://raw.githubusercontent.com/duythien0912/sample_short_video/main/m3u8/video10.m3u8",
    "https://raw.githubusercontent.com/duythien0912/sample_short_video/main/m3u8/video11.m3u8",
    "https://raw.githubusercontent.com/duythien0912/sample_short_video/main/m3u8/video12.m3u8",
    "https://raw.githubusercontent.com/duythien0912/sample_short_video/main/m3u8/video13.m3u8",
    "https://raw.githubusercontent.com/duythien0912/sample_short_video/main/m3u8/video14.m3u8",
    "https://raw.githubusercontent.com/duythien0912/sample_short_video/main/m3u8/video15.m3u8",
    "https://raw.githubusercontent.com/duythien0912/sample_short_video/main/m3u8/video16.m3u8",
    "https://raw.githubusercontent.com/duythien0912/sample_short_video/main/m3u8/video17.m3u8",
    "https://raw.githubusercontent.com/duythien0912/sample_short_video/main/m3u8/video18.m3u8",
    "https://raw.githubusercontent.com/duythien0912/sample_short_video/main/m3u8/video19.m3u8",
    //
    "https://raw.githubusercontent.com/duythien0912/sample_short_video/main/m3u8/video20.m3u8",
    "https://raw.githubusercontent.com/duythien0912/sample_short_video/main/m3u8/video21.m3u8",
    "https://raw.githubusercontent.com/duythien0912/sample_short_video/main/m3u8/video22.m3u8",
    "https://raw.githubusercontent.com/duythien0912/sample_short_video/main/m3u8/video23.m3u8",
    "https://raw.githubusercontent.com/duythien0912/sample_short_video/main/m3u8/video24.m3u8",
    "https://raw.githubusercontent.com/duythien0912/sample_short_video/main/m3u8/video25.m3u8",
    "https://raw.githubusercontent.com/duythien0912/sample_short_video/main/m3u8/video26.m3u8",
    "https://raw.githubusercontent.com/duythien0912/sample_short_video/main/m3u8/video27.m3u8",
    "https://raw.githubusercontent.com/duythien0912/sample_short_video/main/m3u8/video28.m3u8",
    "https://raw.githubusercontent.com/duythien0912/sample_short_video/main/m3u8/video29.m3u8",
    //
    "https://raw.githubusercontent.com/duythien0912/sample_short_video/main/m3u8/video30.m3u8",
    "https://raw.githubusercontent.com/duythien0912/sample_short_video/main/m3u8/video31.m3u8",
    "https://raw.githubusercontent.com/duythien0912/sample_short_video/main/m3u8/video33.m3u8",
  ],
  "total_results": 366723,
  "next_page":
      "https://api.pexels.com/v1/videos/popular/?page=2\u0026per_page=50",
  "url": "https://api-server.pexels.com/videos/",
};
